-- MySQL Script generated by MySQL Workbench
-- 03/06/15 16:12:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EoDdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EoDdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EoDdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `EoDdb` ;

-- -----------------------------------------------------
-- Table `EoDdb`.`Buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EoDdb`.`Buildings` (
  `idBuildings` INT NOT NULL,
  `BuildingName` VARCHAR(45) NULL,
  `BuildingAddress` VARCHAR(45) NULL,
  PRIMARY KEY (`idBuildings`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EoDdb`.`OutsideTemperature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EoDdb`.`OutsideTemperature` (
  `Buildings_idBuildings` INT NOT NULL,
  `Degrees` INT NULL,
  `Units` TEXT(6) NULL,
  `Date/Time` DATETIME NULL,
  PRIMARY KEY (`Buildings_idBuildings`),
  CONSTRAINT `fk_OutsideTemperature_Buildings1`
    FOREIGN KEY (`Buildings_idBuildings`)
    REFERENCES `EoDdb`.`Buildings` (`idBuildings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EoDdb`.`ElectricityDemand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EoDdb`.`ElectricityDemand` (
  `Buildings_idBuildings` INT NOT NULL,
  `Demand` INT NULL,
  `Units` TEXT(6) NULL,
  `Date/Time` DATETIME NULL,
  PRIMARY KEY (`Buildings_idBuildings`),
  CONSTRAINT `fk_ElectricityDemand_Buildings1`
    FOREIGN KEY (`Buildings_idBuildings`)
    REFERENCES `EoDdb`.`Buildings` (`idBuildings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EoDdb`.`ElectricityUsage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EoDdb`.`ElectricityUsage` (
  `Buildings_idBuildings` INT NOT NULL,
  `Usage` INT NULL,
  `Units` TEXT(6) NULL,
  `Date/Time` DATETIME NULL,
  PRIMARY KEY (`Buildings_idBuildings`),
  CONSTRAINT `fk_ElectricityUsage_Buildings1`
    FOREIGN KEY (`Buildings_idBuildings`)
    REFERENCES `EoDdb`.`Buildings` (`idBuildings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EoDdb`.`GasConsumption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EoDdb`.`GasConsumption` (
  `Buildings_idBuildings` INT NOT NULL,
  `Consumed` INT NULL,
  `Units` TEXT(6) NULL,
  `Date/Time` DATETIME NULL,
  PRIMARY KEY (`Buildings_idBuildings`),
  CONSTRAINT `fk_GasConsumption_Buildings1`
    FOREIGN KEY (`Buildings_idBuildings`)
    REFERENCES `EoDdb`.`Buildings` (`idBuildings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EoDdb`.`WaterUsage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EoDdb`.`WaterUsage` (
  `Buildings_idBuildings` INT NOT NULL,
  `Used` INT NULL,
  `Units` TEXT(6) NULL,
  `Date/Time` DATETIME NULL,
  PRIMARY KEY (`Buildings_idBuildings`),
  CONSTRAINT `fk_WaterUsage_Buildings1`
    FOREIGN KEY (`Buildings_idBuildings`)
    REFERENCES `EoDdb`.`Buildings` (`idBuildings`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
